# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 13:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='title',
            new_name='content',
        ),
    ]
