# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170622_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='aaa', max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='url',
            field=models.URLField(default='aaa'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(max_length=200),
        ),
    ]
