# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170623_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(default='aaa', max_length=200),
        ),
    ]
