# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pid',
            field=models.IntegerField(default=0),
        ),
    ]
